language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - git clone https://github.com/frugalos/liberasurecode
  - cd liberasurecode/ && sudo ./install_deps.sh
